import { Link } from "react-router-dom";
import {
  AlertTriangle,
  Blocks,
  CircleSlash,
  FolderTree,
  LayoutGrid,
  Loader,
  Palette,
  Plug,
  SquareStack,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

const STATIC_PAGES = [
  {
    to: "/static/not-found",
    icon: CircleSlash,
    label: "404",
    description: "Shown for any route that doesn't match — try a bad URL.",
  },
  {
    to: "/static/error",
    icon: AlertTriangle,
    label: "Error",
    description: "The route errorElement fallback for render-time errors.",
  },
  {
    to: "/static/loading",
    icon: Loader,
    label: "Loading",
    description: "Full-page skeleton state for async page loads.",
  },
  {
    to: "/static/empty-state",
    icon: LayoutGrid,
    label: "Empty state",
    description: "Used by the dashboard when a list has zero items.",
  },
] as const;

const STRUCTURE_ITEMS = [
  {
    icon: FolderTree,
    label: "components/ui/",
    description:
      "Curated Shadcn primitives — button, input, card, table, dialog, form, and more. Generic, reusable, not specific to this app.",
  },
  {
    icon: Blocks,
    label: "components/common/",
    description: "App-level shared layout: app-shell.tsx, nav-sidebar.tsx.",
  },
  {
    icon: Plug,
    label: "lib/api-client/, lib/hooks/",
    description:
      "The ApiClient interface + mock/real implementations, and the TanStack Query hooks that wrap it.",
  },
  {
    icon: LayoutGrid,
    label: "pages/",
    description:
      "dashboard/ (sample CRUD), showcase/ (every UI primitive), static/ (404, error, loading, empty-state).",
  },
] as const;

const NEXT_STEPS = [
  "Explore the sample dashboard — create, edit, and delete items against mock data.",
  "Browse every UI primitive at once on the Components page.",
  "Open src/styles/theme.css and change --color-primary — watch it apply everywhere.",
  "Add your own page under src/pages/, then wire a route in App.tsx and a link in nav-sidebar.tsx.",
] as const;

export default function LandingPage() {
  return (
    <div className="flex flex-col gap-xl">
      <div className="flex flex-col gap-sm">
        <h1 className="text-display-sm font-semibold text-ink">
          {import.meta.env.VITE_APP_NAME}
        </h1>
        <p className="max-w-[36rem] text-body-md text-body">
          A React + TypeScript + Vite + Shadcn/ui dashboard, generated by
          Forge Web. This page is your map — everything below is a working
          pattern you copy from, not a fixed skeleton.
        </p>
        <div className="flex gap-sm pt-xs">
          <Button asChild>
            <Link to="/dashboard">View Dashboard</Link>
          </Button>
          <Button asChild variant="secondary">
            <Link to="/components">Browse Components</Link>
          </Button>
        </div>
      </div>

      <section className="flex flex-col gap-base">
        <h2 className="text-title-sm font-semibold text-ink">
          Project structure
        </h2>
        <div className="grid grid-cols-1 gap-base sm:grid-cols-2">
          {STRUCTURE_ITEMS.map(({ icon: Icon, label, description }) => (
            <Card key={label}>
              <CardHeader className="flex-row items-start gap-sm space-y-0">
                <Icon className="size-5 shrink-0 text-primary" />
                <div className="flex flex-col gap-xs">
                  <CardTitle className="text-body-md">{label}</CardTitle>
                  <CardDescription>{description}</CardDescription>
                </div>
              </CardHeader>
            </Card>
          ))}
        </div>
      </section>

      <section className="flex flex-col gap-base">
        <h2 className="text-title-sm font-semibold text-ink">
          Mock vs. real API
        </h2>
        <Card className="max-w-[36rem]">
          <CardContent className="flex flex-col gap-sm pt-lg">
            <p className="text-body-sm text-body">
              Every data operation goes through the <code>ApiClient</code>{" "}
              interface in <code>lib/api-client/</code>, never a direct{" "}
              <code>fetch</code> call from a component. Switching from mock
              data to a real backend is a <code>.env</code> edit, not a code
              change:
            </p>
            <pre className="rounded-sm border border-hairline bg-surface-soft p-base text-body-sm text-ink">
              {"VITE_API_MODE=true\nVITE_API_BASE_URL=http://localhost:8080/api"}
            </pre>
          </CardContent>
        </Card>
      </section>

      <section className="flex flex-col gap-base">
        <h2 className="text-title-sm font-semibold text-ink">Theming</h2>
        <Card className="max-w-[36rem]">
          <CardHeader className="flex-row items-start gap-sm space-y-0">
            <Palette className="size-5 shrink-0 text-primary" />
            <div className="flex flex-col gap-xs">
              <CardTitle className="text-body-md">
                One file, the whole app
              </CardTitle>
              <CardDescription>
                Every color, font size, spacing step, radius, and shadow is a
                CSS custom property in <code>src/styles/theme.css</code> —
                edit it there and the change applies everywhere at once. See
                it in action on the{" "}
                <Link to="/components" className="text-link underline">
                  Components
                </Link>{" "}
                page.
              </CardDescription>
            </div>
          </CardHeader>
        </Card>
      </section>

      <section className="flex flex-col gap-base">
        <h2 className="text-title-sm font-semibold text-ink">Static pages</h2>
        <p className="max-w-[36rem] text-body-sm text-muted">
          Reference screens generated alongside the dashboard — preview each
          one below.
        </p>
        <div className="grid grid-cols-1 gap-base sm:grid-cols-2">
          {STATIC_PAGES.map(({ to, icon: Icon, label, description }) => (
            <Link key={to} to={to}>
              <Card className="transition-colors hover:bg-surface-soft">
                <CardHeader className="flex-row items-start gap-sm space-y-0">
                  <Icon className="size-5 shrink-0 text-primary" />
                  <div className="flex flex-col gap-xs">
                    <CardTitle className="text-body-md">{label}</CardTitle>
                    <CardDescription>{description}</CardDescription>
                  </div>
                </CardHeader>
              </Card>
            </Link>
          ))}
        </div>
      </section>

      <section className="flex flex-col gap-base">
        <h2 className="text-title-sm font-semibold text-ink">Next steps</h2>
        <ul className="flex flex-col gap-sm">
          {NEXT_STEPS.map((step) => (
            <li
              key={step}
              className="flex items-start gap-sm text-body-sm text-body"
            >
              <SquareStack className="mt-0.5 size-4 shrink-0 text-primary" />
              {step}
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
